title: SlaXx Blog
iconURL: assets/default-icon.png
theme: jekyll-theme-leaf

# for a clean URL
permalink: :slug

social:
  twitter: SlaXxCho
  github: SlaXxCho

plugins:
 - jekyll-feed
 - jekyll-seo-tag

### comments & analytics
hyvor_talk_website_id: 8408
google_analytics: UA-NNNNNNNN-N
